name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v6
      - name: Install, build, and upload your site output
        uses: withastro/action@44706356b4eb735f8b9035699eb4796241a040c4 # Pinned on 9 April 2026
      - name: Deploy
        uses: cloudflare/wrangler-action@707f63750981584eb6abc365a50d441516fb04b8 # Pinned on 9 April 2026
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: latest